// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"architecture.mdx": () => import("../src/content/docs/architecture.mdx?collection=docs"), "index.mdx": () => import("../src/content/docs/index.mdx?collection=docs"), "quickstart.mdx": () => import("../src/content/docs/quickstart.mdx?collection=docs"), "aichat/conversation-flow.mdx": () => import("../src/content/docs/aichat/conversation-flow.mdx?collection=docs"), "aichat/data-models.mdx": () => import("../src/content/docs/aichat/data-models.mdx?collection=docs"), "aichat/overview.mdx": () => import("../src/content/docs/aichat/overview.mdx?collection=docs"), "aichat/ui-ux.mdx": () => import("../src/content/docs/aichat/ui-ux.mdx?collection=docs"), "customization/themes.mdx": () => import("../src/content/docs/customization/themes.mdx?collection=docs"), "deployment/ci-cd.mdx": () => import("../src/content/docs/deployment/ci-cd.mdx?collection=docs"), "deployment/docker.mdx": () => import("../src/content/docs/deployment/docker.mdx?collection=docs"), "deployment/production-setup.mdx": () => import("../src/content/docs/deployment/production-setup.mdx?collection=docs"), "deployment/vercel.mdx": () => import("../src/content/docs/deployment/vercel.mdx?collection=docs"), "development/api-development.mdx": () => import("../src/content/docs/development/api-development.mdx?collection=docs"), "development/configuration.mdx": () => import("../src/content/docs/development/configuration.mdx?collection=docs"), "development/database-development.mdx": () => import("../src/content/docs/development/database-development.mdx?collection=docs"), "development/project-structure.mdx": () => import("../src/content/docs/development/project-structure.mdx?collection=docs"), "features/authentication.mdx": () => import("../src/content/docs/features/authentication.mdx?collection=docs"), "features/file-management.mdx": () => import("../src/content/docs/features/file-management.mdx?collection=docs"), "features/payment-billing.mdx": () => import("../src/content/docs/features/payment-billing.mdx?collection=docs"), }),
};
export default browserCollections;